[build]
jobs = 8

[unstable]
binary-dep-depinfo = true
# build-std = ["panic_abort", "std"]
# build-std-features = ["panic_immediate_abort"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
